version: '3.8'

services:
  nodeapp:
    build: .
    container_name: nodeapp
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
