version: '3.8'

services:
  nodeapp:
    build: .
    container_name: nodeapp
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/movies
      - TMDB_BASE_URL=https://api.themoviedb.org/
      - TMDB_API_KEY=7b0c5fc9d6fd712e621559860b6d2556

  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
